dependencies:
- python>=3.5           # Necessary for plda.
- numpy~=1.14.2         # Necessary for plda.
- scipy~=1.0.1          # Necessary for plda.
- scikit-learn~=0.19.1  # Necessary for plda.
- pytest~=3.6.2         # Optional: for testing.
- pycodestyle~=2.4.0    # Optional: for contributing.
- matplotlib~=2.2.2     # Optional: for the demo.
- nb_conda~=2.2.1       # Optional: for the demo.
- jupyter~=1.0.0        # Optional: for the demo.
- pip=20.2.1            # Necessary for installation.
- pip:
  - https://github.com/RaviSoji/plda/tarball/master
